name: landscaperecord
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6

  # Network & API
  http: ^1.2.0

  # Maps & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0

  # Image Handling
  image_picker: ^1.0.4
  image: ^4.1.3

  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
